TodoApp/urls.py
from django.contrib import admin
from django.urls import path, include


app_name = 'TodoApp'
urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('add_task/', views.add_task, name='add_task'),
    path('delete_task/<int:task_id>', views.delete_task, name='delete_task'),
    path('open_task/<int:task_id>', views.open_task, name='open_task'),
    path('close_task/<int:task_id>', views.close_task, name='close_task'),
]

main/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Task(models.Model):
    text = models.CharField(max_length=200)
    added_time = models.DateTimeField(default=timezone.now)
    #remaining_days = models.IntegerField(default=1)
    status = models.CharField(max_length=50, default='Not Started')

    def __str__(self):
        return self.text+','+self.status

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Task

# Create your views here.

def home(request):
    content = { 'tasks': Task.objects.all().order_by('-status','-added_time') }
    return render(request, 'main/home.html', content)

def add_task(request):
    new_task_text = request.POST['task_text']
    new_task = Task(text=new_task_text, status='Not Started')
    new_task.save()
    return HttpResponseRedirect('/')

def delete_task(request, task_id):
    print(task_id)
    taskToDel = Task.objects.get(pk=task_id)
    print(taskToDel)
    taskToDel.delete()
    return HttpResponseRedirect('/')

def open_task(requset, task_id):
    print(task_id)
    task = Task.objects.get(pk=task_id)
    task.status = 'In Progress'
    task.save()
    return HttpResponseRedirect('/')

def close_task(request, task_id):
    print(task_id)
    task = Task.objects.get(pk=task_id)
    task.status = 'Finished'
    print(task)
    task.save()
    return HttpResponseRedirect('/')

main/templates/main/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>

<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo center">My Todo App</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="sass.html"></a></li>
            <li><a href="badges.html"></a></li>
            <li><a href="collapsible.html"></a></li>
        </ul>
    </div>
</nav>

<div class="container">


    <div class="row">
        <form action="{% url 'main:add_task' %}" method="post" class="col s12">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s8">
                    <i class="material-icons prefix">mode_edit</i>
                    <textarea name="task_text" id="icon_prefix2" class="materialize-textarea"></textarea>
                    <label for="icon_prefix2">New Task</label>
                </div>
                <button style="margin:20px" class="btn waves-effect waves-light" type="submit" name="action">Add
                    <i class="material-icons right">send</i>
                </button>
            </div>
        </form>
    </div>


    <table class="highlight">
        <thead>
        <tr>
            <th>Task</th>
            <th style="text-align: center;"></th>
            <th style="text-align: center;">Status</thc>
        </tr>
        </thead>

        <tbody>
        {% for task in tasks %}
        <tr>
            <td class="col s12">{{ task.text|safe }}
            </td>
            <td>
                {% if task.status == 'Not Started' %}
                <form action="{% url 'main:open_task' task.id %}" method="post">
                    {% csrf_token %}
                    <button class="waves-effect light-green accent-4 btn-small right">open</button>
                </form>
                {% endif %}
                {% if task.status == 'In Progress' %}
                <form action="{% url 'main:close_task' task.id %}" method="post">
                    {% csrf_token %}
                    <button class="waves-effect waves-light orange darken-4 btn-small right">close</button>
                </form>
                {% endif %}
            </td>
            <td style="text-align: center;">{{ task.status }}</td>
            <form action="delete_task/{{ task.id }}" method="post">
                {% csrf_token %}
                <td>
                    <button class="waves-effect red darken-4 btn" type="submit" name="action">Delete</button>
                </td>
            </form>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
<script src="{% static 'tinymce/js/prism.js' %}"></script>

</html>